### ISSUE TITLE
@synchronize missing

### ISSUE THREAD

**Issue by reversi-fun** [bebac/thread-priority-queue#1]
when run 'test_thread_priority_queue.rb'  then cause Error.
May Be Ruby 'thread' interface is brokend.

my Ruby version is ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]

```
Error: test_left_shift_must_be_obj_prio_tuple(TestPriorityQueueBase): NoMethodError: undefined method `synchronize' for nil:NilClass
queueTest/thread-priority-queue-master/lib/thread_priority_queue.rb:8:in `push'
queueTest/thread-priority-queue-master/lib/thread_priority_queue.rb:20:in `<<'
test_thread_priority_queue.rb:33:in `test_left_shift_must_be_obj_prio_tuple'
     30:   end
     31:
     32:   def test_left_shift_must_be_obj_prio_tuple
  => 33:     @q << [ 'a', 2 ]
     34:     @q << [ 'b', 1 ]
     35:     assert_equal 2, @q.length
     36:     # Test that items comes out in prioritized order.
================================================================
```

**Comment by bebac** [comment]
It seems `Queue` is implemented in c in Ruby 2. I have ported the queue code from 1.9, so that `PriorityQueue` no longer inherits from `Queue`. The tests are passing for me on:

ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
